using DAL.DAO;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class BlogPost
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)] // Indicates the ID is not auto-generated by the DB
    public string Id { get; set; }

    [Required]
    [MaxLength(250)]
    public string Title { get; set; }

    [Required]
    public string Excerpt { get; set; }

    [Required]
    public string Content { get; set; }

    public DateTime Date { get; set; }

    [Required]
    [MaxLength(100)]
    public string Author { get; set; }

    [Required]
    public string ImageUrl { get; set; }

    public bool IsFeatured { get; set; } = false;

    public bool IsDeleted { get; set; } = false;

    // Navigation property for comments
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}